### ISSUE TITLE
ДЗ5

### ISSUE THREAD

**Issue by artem-linenko** [Kolland/Kolland.github.io#2]
1. Що це за назва класу .inputstyle? І навіщо він взагалі потрібен?
2. Навіщо потрібні обгортки .checkbox i .btn якщо до цього для всіх інпутів ти обійшовся без обгорток?

**Comment by Kolland** [comment]
``` html
<div class="checkbox">
    <input type="checkbox" name="send_upd" id="send_upd">
    <label for="send_upd">Send me Youbike updates and tips</label>
</div>

<input class="inputstyle" type="text" name="first_name" required placeholder="First Name">
```

``` css
.inputstyle {                               /*is for styling text fields*/
    width: 257px;
    height: 35px;
    padding-left: 19px;
    margin: 0 auto;
    margin-top: 16px;
    display: block;
    background-color: #000;
    border: none;
    border-bottom: 1px solid #4a4948;
    font-size: 14px;
    color:white;
}
.checkbox {                                     /*is for align checkbox and his title in one line*/
    margin-top: 20px;
    margin-left: 142px;
    color: #cccccc;
    font-size: 14px;    
}
.checkbox label,.checkbox input{
    vertical-align:middle;
    margin: 0;
    cursor: pointer;
}
```

+deleted wrapper for btn
